/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_content_schedule_contentSchedule_delete_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_content_schedule_contentSchedule_delete_result$schema = z.object({
  'file': z.string().readonly(),
  'items': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'date': z.string().readonly(),
  'time': z.union([z.literal(null), z.string()]).readonly(),
  'platform': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("draft"), z.literal("published"), z.literal("scheduled"), z.literal("idea")]).readonly(),
  'kind': z.union([z.literal("content"), z.literal("event")]).readonly(),
  'topic': z.union([z.literal(null), z.string()]).readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
})).readonly(),
  'problems': z.array(z.string()).readonly(),
})
const _deepseek_ai_dsh_content_schedule_contentSchedule_getNotes_result$schema = z.object({
  'file': z.string().readonly(),
  'notes': z.record(z.string(), z.object({
  'text': z.string().readonly(),
  'updatedAt': z.string().readonly(),
})).readonly().readonly(),
  'problems': z.array(z.string()).readonly(),
})
const _deepseek_ai_dsh_content_schedule_contentSchedule_list_result$schema = z.object({
  'file': z.string().readonly(),
  'items': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'date': z.string().readonly(),
  'time': z.union([z.literal(null), z.string()]).readonly(),
  'platform': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("draft"), z.literal("published"), z.literal("scheduled"), z.literal("idea")]).readonly(),
  'kind': z.union([z.literal("content"), z.literal("event")]).readonly(),
  'topic': z.union([z.literal(null), z.string()]).readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
})).readonly(),
  'problems': z.array(z.string()).readonly(),
})
const _deepseek_ai_dsh_content_schedule_contentSchedule_put_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'title': z.string().readonly(),
  'date': z.string().readonly(),
  'time': z.union([z.literal(null), z.string()]).readonly(),
  'platform': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("draft"), z.literal("published"), z.literal("scheduled"), z.literal("idea")]).readonly(),
  'kind': z.union([z.literal("content"), z.literal("event")]).readonly(),
  'topic': z.union([z.literal(null), z.string()]).readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
})
const _deepseek_ai_dsh_content_schedule_contentSchedule_put_result$schema = z.object({
  'file': z.string().readonly(),
  'items': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'date': z.string().readonly(),
  'time': z.union([z.literal(null), z.string()]).readonly(),
  'platform': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("draft"), z.literal("published"), z.literal("scheduled"), z.literal("idea")]).readonly(),
  'kind': z.union([z.literal("content"), z.literal("event")]).readonly(),
  'topic': z.union([z.literal(null), z.string()]).readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
})).readonly(),
  'problems': z.array(z.string()).readonly(),
})
const _deepseek_ai_dsh_content_schedule_contentSchedule_putNote_parameter_0$schema = z.string()
const _deepseek_ai_dsh_content_schedule_contentSchedule_putNote_parameter_1$schema = z.string()
const _deepseek_ai_dsh_content_schedule_contentSchedule_putNote_result$schema = z.object({
  'file': z.string().readonly(),
  'notes': z.record(z.string(), z.object({
  'text': z.string().readonly(),
  'updatedAt': z.string().readonly(),
})).readonly().readonly(),
  'problems': z.array(z.string()).readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-content-schedule',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-content-schedule#contentSchedule/delete',
      service: 'contentSchedule',
      namespace: 'contentSchedule',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-content-schedule#contentSchedule/delete:id',
            schema: _deepseek_ai_dsh_content_schedule_contentSchedule_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-content-schedule/types#ContentScheduleSnapshot',
        schema: _deepseek_ai_dsh_content_schedule_contentSchedule_delete_result$schema,
      },
      sourceLocation: {"file":"packages/creation/content-schedule/src/index.ts","line":88,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-content-schedule#contentSchedule/getNotes',
      service: 'contentSchedule',
      namespace: 'contentSchedule',
      method: 'getNotes',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-content-schedule/types#CalendarNotesSnapshot',
        schema: _deepseek_ai_dsh_content_schedule_contentSchedule_getNotes_result$schema,
      },
      sourceLocation: {"file":"packages/creation/content-schedule/src/index.ts","line":97,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-content-schedule#contentSchedule/list',
      service: 'contentSchedule',
      namespace: 'contentSchedule',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-content-schedule/types#ContentScheduleSnapshot',
        schema: _deepseek_ai_dsh_content_schedule_contentSchedule_list_result$schema,
      },
      sourceLocation: {"file":"packages/creation/content-schedule/src/index.ts","line":58,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-content-schedule#contentSchedule/put',
      service: 'contentSchedule',
      namespace: 'contentSchedule',
      method: 'put',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-content-schedule/types#ScheduleItemInput',
            schema: _deepseek_ai_dsh_content_schedule_contentSchedule_put_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-content-schedule/types#ContentScheduleSnapshot',
        schema: _deepseek_ai_dsh_content_schedule_contentSchedule_put_result$schema,
      },
      sourceLocation: {"file":"packages/creation/content-schedule/src/index.ts","line":70,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-content-schedule#contentSchedule/putNote',
      service: 'contentSchedule',
      namespace: 'contentSchedule',
      method: 'putNote',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-content-schedule#contentSchedule/putNote:id',
            schema: _deepseek_ai_dsh_content_schedule_contentSchedule_putNote_parameter_0$schema,
          },
        },
        {
          name: 'text',
          wire: 'text',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-content-schedule#contentSchedule/putNote:text',
            schema: _deepseek_ai_dsh_content_schedule_contentSchedule_putNote_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-content-schedule/types#CalendarNotesSnapshot',
        schema: _deepseek_ai_dsh_content_schedule_contentSchedule_putNote_result$schema,
      },
      sourceLocation: {"file":"packages/creation/content-schedule/src/index.ts","line":110,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
