/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ContentScheduleSnapshot, ScheduleItem, ScheduleItemInput } from '@deepseek-ai/dsh-content-schedule/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$636f6e74656e745363686564756c65 {
    delete: (id: ScheduleItem['id']) => Promise<RemoteResult<ContentScheduleSnapshot>>
    list: () => Promise<RemoteResult<ContentScheduleSnapshot>>
    put: (input: ScheduleItemInput) => Promise<RemoteResult<ContentScheduleSnapshot>>
  }
  interface TypertRemoteMap {
    'contentSchedule/delete': (id: ScheduleItem['id']) => Promise<RemoteResult<ContentScheduleSnapshot>>
    'contentSchedule/list': () => Promise<RemoteResult<ContentScheduleSnapshot>>
    'contentSchedule/put': (input: ScheduleItemInput) => Promise<RemoteResult<ContentScheduleSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'contentSchedule': TypertRemoteNamespace$636f6e74656e745363686564756c65
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
