/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_content_topics_contentTopics_delete_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_content_topics_contentTopics_delete_result$schema = z.object({
  'file': z.string().readonly(),
  'items': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'oneLiner': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("done"), z.literal("idea"), z.literal("todo"), z.literal("creating"), z.literal("shelved")]).readonly(),
  'source': z.object({
  'type': z.union([z.literal("manual"), z.literal("gather"), z.literal("benchmark")]).readonly(),
  'refId': z.union([z.literal(null), z.string()]).readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snapshot': z.union([z.literal(null), z.object({
  'title': z.string().readonly(),
  'summary': z.union([z.literal(null), z.string()]).readonly(),
  'capturedAt': z.string().readonly(),
})]).readonly(),
}).readonly(),
  'tags': z.array(z.string()).readonly(),
  'description': z.union([z.literal(null), z.string()]).readonly(),
  'score': z.union([z.literal(null), z.object({
  'total': z.number().readonly(),
  'source': z.union([z.literal("manual"), z.literal("ai")]).readonly(),
  'factors': z.union([z.literal(null), z.array(z.object({
  'name': z.string().readonly(),
  'score': z.number().readonly(),
  'reason': z.union([z.literal(null), z.string()]).readonly(),
  'confidence': z.number().readonly(),
  'estimated': z.boolean().readonly(),
}))]).readonly(),
  'evaluatedAt': z.string().readonly(),
})]).readonly(),
  'planDate': z.union([z.literal(null), z.string()]).readonly(),
  'scheduleItemId': z.union([z.literal(null), z.string()]).readonly(),
  'topicDir': z.union([z.literal(null), z.string()]).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
})).readonly(),
  'problems': z.array(z.string()).readonly(),
})
const _deepseek_ai_dsh_content_topics_contentTopics_list_result$schema = z.object({
  'file': z.string().readonly(),
  'items': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'oneLiner': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("done"), z.literal("idea"), z.literal("todo"), z.literal("creating"), z.literal("shelved")]).readonly(),
  'source': z.object({
  'type': z.union([z.literal("manual"), z.literal("gather"), z.literal("benchmark")]).readonly(),
  'refId': z.union([z.literal(null), z.string()]).readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snapshot': z.union([z.literal(null), z.object({
  'title': z.string().readonly(),
  'summary': z.union([z.literal(null), z.string()]).readonly(),
  'capturedAt': z.string().readonly(),
})]).readonly(),
}).readonly(),
  'tags': z.array(z.string()).readonly(),
  'description': z.union([z.literal(null), z.string()]).readonly(),
  'score': z.union([z.literal(null), z.object({
  'total': z.number().readonly(),
  'source': z.union([z.literal("manual"), z.literal("ai")]).readonly(),
  'factors': z.union([z.literal(null), z.array(z.object({
  'name': z.string().readonly(),
  'score': z.number().readonly(),
  'reason': z.union([z.literal(null), z.string()]).readonly(),
  'confidence': z.number().readonly(),
  'estimated': z.boolean().readonly(),
}))]).readonly(),
  'evaluatedAt': z.string().readonly(),
})]).readonly(),
  'planDate': z.union([z.literal(null), z.string()]).readonly(),
  'scheduleItemId': z.union([z.literal(null), z.string()]).readonly(),
  'topicDir': z.union([z.literal(null), z.string()]).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
})).readonly(),
  'problems': z.array(z.string()).readonly(),
})
const _deepseek_ai_dsh_content_topics_contentTopics_put_parameter_0$schema = z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly().optional(),
  'title': z.string().readonly(),
  'oneLiner': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("done"), z.literal("idea"), z.literal("todo"), z.literal("creating"), z.literal("shelved")]).readonly(),
  'source': z.object({
  'type': z.union([z.literal("manual"), z.literal("gather"), z.literal("benchmark")]).readonly(),
  'refId': z.union([z.literal(null), z.string()]).readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snapshot': z.union([z.literal(null), z.object({
  'title': z.string().readonly(),
  'summary': z.union([z.literal(null), z.string()]).readonly(),
  'capturedAt': z.string().readonly(),
})]).readonly(),
}).readonly(),
  'tags': z.array(z.string()).readonly(),
  'description': z.union([z.literal(null), z.string()]).readonly(),
  'score': z.union([z.literal(null), z.object({
  'total': z.number().readonly(),
  'source': z.union([z.literal("manual"), z.literal("ai")]).readonly(),
  'factors': z.union([z.literal(null), z.array(z.object({
  'name': z.string().readonly(),
  'score': z.number().readonly(),
  'reason': z.union([z.literal(null), z.string()]).readonly(),
  'confidence': z.number().readonly(),
  'estimated': z.boolean().readonly(),
}))]).readonly(),
  'evaluatedAt': z.string().readonly(),
})]).readonly(),
  'planDate': z.union([z.literal(null), z.string()]).readonly(),
  'scheduleItemId': z.union([z.literal(null), z.string()]).readonly(),
  'topicDir': z.union([z.literal(null), z.string()]).readonly(),
})
const _deepseek_ai_dsh_content_topics_contentTopics_put_result$schema = z.object({
  'file': z.string().readonly(),
  'items': z.array(z.object({
  'id': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'oneLiner': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("done"), z.literal("idea"), z.literal("todo"), z.literal("creating"), z.literal("shelved")]).readonly(),
  'source': z.object({
  'type': z.union([z.literal("manual"), z.literal("gather"), z.literal("benchmark")]).readonly(),
  'refId': z.union([z.literal(null), z.string()]).readonly(),
  'url': z.union([z.literal(null), z.string()]).readonly(),
  'snapshot': z.union([z.literal(null), z.object({
  'title': z.string().readonly(),
  'summary': z.union([z.literal(null), z.string()]).readonly(),
  'capturedAt': z.string().readonly(),
})]).readonly(),
}).readonly(),
  'tags': z.array(z.string()).readonly(),
  'description': z.union([z.literal(null), z.string()]).readonly(),
  'score': z.union([z.literal(null), z.object({
  'total': z.number().readonly(),
  'source': z.union([z.literal("manual"), z.literal("ai")]).readonly(),
  'factors': z.union([z.literal(null), z.array(z.object({
  'name': z.string().readonly(),
  'score': z.number().readonly(),
  'reason': z.union([z.literal(null), z.string()]).readonly(),
  'confidence': z.number().readonly(),
  'estimated': z.boolean().readonly(),
}))]).readonly(),
  'evaluatedAt': z.string().readonly(),
})]).readonly(),
  'planDate': z.union([z.literal(null), z.string()]).readonly(),
  'scheduleItemId': z.union([z.literal(null), z.string()]).readonly(),
  'topicDir': z.union([z.literal(null), z.string()]).readonly(),
  'createdAt': z.string().readonly(),
  'updatedAt': z.string().readonly(),
})).readonly(),
  'problems': z.array(z.string()).readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-content-topics',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-content-topics#contentTopics/delete',
      service: 'contentTopics',
      namespace: 'contentTopics',
      method: 'delete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-content-topics#contentTopics/delete:id',
            schema: _deepseek_ai_dsh_content_topics_contentTopics_delete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-content-topics/types#ContentTopicsSnapshot',
        schema: _deepseek_ai_dsh_content_topics_contentTopics_delete_result$schema,
      },
      sourceLocation: {"file":"packages/creation/content-topics/src/index.ts","line":81,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-content-topics#contentTopics/list',
      service: 'contentTopics',
      namespace: 'contentTopics',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-content-topics/types#ContentTopicsSnapshot',
        schema: _deepseek_ai_dsh_content_topics_contentTopics_list_result$schema,
      },
      sourceLocation: {"file":"packages/creation/content-topics/src/index.ts","line":51,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-content-topics#contentTopics/put',
      service: 'contentTopics',
      namespace: 'contentTopics',
      method: 'put',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'input',
          wire: 'input',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-content-topics/types#TopicItemInput',
            schema: _deepseek_ai_dsh_content_topics_contentTopics_put_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-content-topics/types#ContentTopicsSnapshot',
        schema: _deepseek_ai_dsh_content_topics_contentTopics_put_result$schema,
      },
      sourceLocation: {"file":"packages/creation/content-topics/src/index.ts","line":63,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
