/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ContentTopicsSnapshot, TopicItem, TopicItemInput } from '@deepseek-ai/dsh-content-topics/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$636f6e74656e74546f70696373 {
    delete: (id: TopicItem['id']) => Promise<RemoteResult<ContentTopicsSnapshot>>
    list: () => Promise<RemoteResult<ContentTopicsSnapshot>>
    put: (input: TopicItemInput) => Promise<RemoteResult<ContentTopicsSnapshot>>
  }
  interface TypertRemoteMap {
    'contentTopics/delete': (id: TopicItem['id']) => Promise<RemoteResult<ContentTopicsSnapshot>>
    'contentTopics/list': () => Promise<RemoteResult<ContentTopicsSnapshot>>
    'contentTopics/put': (input: TopicItemInput) => Promise<RemoteResult<ContentTopicsSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'contentTopics': TypertRemoteNamespace$636f6e74656e74546f70696373
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
