/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_content_outputs_contentOutputs_list_result$schema = z.object({
  'root': z.string().readonly(),
  'projects': z.array(z.object({
  'topic': z.intersection(z.string(), z.unknown()).readonly(),
  'title': z.string().readonly(),
  'kind': z.union([z.literal("article"), z.literal("xhs-note"), z.literal("video"), z.literal("cards"), z.literal("poster"), z.literal("audio"), z.literal("other")]).readonly(),
  'platform': z.union([z.literal(null), z.string()]).readonly(),
  'status': z.union([z.literal("draft"), z.literal("ready"), z.literal("published")]).readonly(),
  'tags': z.array(z.string()).readonly(),
  'summary': z.union([z.literal(null), z.string()]).readonly(),
  'updatedAt': z.string().readonly(),
  'deliverables': z.array(z.string()).readonly(),
  'assetCount': z.number().readonly(),
  'hasMetadata': z.boolean().readonly(),
})).readonly(),
  'problems': z.array(z.object({
  'topic': z.string().readonly(),
  'detail': z.string().readonly(),
})).readonly(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-content-outputs',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-content-outputs#contentOutputs/list',
      service: 'contentOutputs',
      namespace: 'contentOutputs',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-content-outputs/types#ContentOutputsSnapshot',
        schema: _deepseek_ai_dsh_content_outputs_contentOutputs_list_result$schema,
      },
      sourceLocation: {"file":"packages/creation/content-outputs/src/index.ts","line":48,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
