/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ContentOutputsSnapshot } from '@deepseek-ai/dsh-content-outputs/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$636f6e74656e744f757470757473 {
    list: () => Promise<RemoteResult<ContentOutputsSnapshot>>
  }
  interface TypertRemoteMap {
    'contentOutputs/list': () => Promise<RemoteResult<ContentOutputsSnapshot>>
  }
  interface TypertRemoteNamespaceMap {
    'contentOutputs': TypertRemoteNamespace$636f6e74656e744f757470757473
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
