/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { CompetitorAnalyzeWorkRequest, CompetitorAnalyzeWorkResult, CompetitorManifest, CompetitorManifestRead, CompetitorReportRequest, CompetitorReportResult, ContentOutputsSnapshot, CreateAiResult, CreateAssetList, CreateEvaluateRequest, CreateEvaluation, CreateGenerateRequest, CreateManifest, CreatePublishRequest, CreatePublishResult, CreateRegisterRequest, CreateRewriteRequest, CreateStateRead, CreateTemplateInput, CreateTemplateList, GatherAiRequest, GatherAiResult, GatherAssetMove, GatherAssetWrite, GatherFeedRequest, GatherFeedResult, GatherManifest, GatherManifestRead, InteractionClassifyRequest, InteractionClassifyResult, InteractionImportCommitRequest, InteractionImportCommitResult, InteractionImportPreview, InteractionImportPreviewRequest, InteractionInsightRequest, InteractionInsightResult, InteractionReplyRequest, InteractionReplyResult, InteractionSendReplyRequest, InteractionsManifest, InteractionsManifestRead, OutputMetadata, PersonaAiRequest, PersonaAiResult, PersonaEntry, PersonaId, PersonaInput, PersonaReport, PersonasSnapshot, PublishAdaptRequest, PublishAdaptResult, PublishIndexRead, PublishManifest, PublishManifestRead, PublishPackage, PublishProfilesDoc, PublishProfilesRead, ReviewAiResult, ReviewAnalyzeWorkRequest, ReviewGenerateReportRequest, ReviewImportCommitRequest, ReviewImportCommitResult, ReviewImportPreview, ReviewImportPreviewRequest, ReviewIndexRead, ReviewManifest, ReviewManifestRead, ReviewReportRead, ReviewTaskDeleteRequest, TemplateAiRequest, TemplateAiResult, TemplateHistoryRead, TemplateId, TemplateImportStrategy, TemplateImportSummary, TemplateInput, TemplatePack, TemplateRecord, TemplatesSnapshot, TemplateStatus, TemplateTag } from '@deepseek-ai/dsh-content-outputs/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$636f6e74656e744f757470757473 {
    adaptPublishContent: (request: PublishAdaptRequest) => Promise<RemoteResult<PublishAdaptResult>>
    analyzeCompetitorWork: (request: CompetitorAnalyzeWorkRequest) => Promise<RemoteResult<CompetitorAnalyzeWorkResult>>
    analyzeReviewWork: (request: ReviewAnalyzeWorkRequest) => Promise<RemoteResult<ReviewAiResult>>
    buildPublishPackage: (theme: string, taskId: string) => Promise<RemoteResult<PublishPackage>>
    classifyInteractions: (request: InteractionClassifyRequest) => Promise<RemoteResult<InteractionClassifyResult>>
    commitInteractionImport: (request: InteractionImportCommitRequest) => Promise<RemoteResult<InteractionImportCommitResult>>
    commitReviewImport: (request: ReviewImportCommitRequest) => Promise<RemoteResult<ReviewImportCommitResult>>
    deleteAsset: (theme: string, file: string) => Promise<RemoteResult<void>>
    deleteCreateTemplate: (id: string) => Promise<RemoteResult<CreateTemplateList>>
    deletePersona: (id: PersonaId) => Promise<RemoteResult<void>>
    deleteReviewTask: (request: ReviewTaskDeleteRequest) => Promise<RemoteResult<void>>
    deleteTemplate: (id: TemplateId) => Promise<RemoteResult<void>>
    evaluateCreateContent: (request: CreateEvaluateRequest) => Promise<RemoteResult<CreateEvaluation>>
    exportInteractionCsv: () => Promise<RemoteResult<{ text: string; }>>
    exportTemplates: (ids: readonly string[]) => Promise<RemoteResult<TemplatePack>>
    extractInteractionInsights: (request: InteractionInsightRequest) => Promise<RemoteResult<InteractionInsightResult>>
    fetchFeed: (request: GatherFeedRequest, signal?: AbortSignal) => Promise<RemoteResult<GatherFeedResult>>
    generateCompetitorReport: (request: CompetitorReportRequest) => Promise<RemoteResult<CompetitorReportResult>>
    generateCreateContent: (request: CreateGenerateRequest) => Promise<RemoteResult<CreateAiResult>>
    generateInteractionReply: (request: InteractionReplyRequest) => Promise<RemoteResult<InteractionReplyResult>>
    generateReviewReport: (request: ReviewGenerateReportRequest) => Promise<RemoteResult<ReviewAiResult>>
    getPersona: (id: PersonaId) => Promise<RemoteResult<{ persona?: PersonaEntry; }>>
    getTemplateHistory: (id: TemplateId) => Promise<RemoteResult<TemplateHistoryRead>>
    importTemplates: (pack: TemplatePack, strategy: TemplateImportStrategy) => Promise<RemoteResult<TemplateImportSummary>>
    list: () => Promise<RemoteResult<ContentOutputsSnapshot>>
    listCreateAssets: (theme: string) => Promise<RemoteResult<CreateAssetList>>
    listCreateTemplates: () => Promise<RemoteResult<CreateTemplateList>>
    listPersonas: () => Promise<RemoteResult<PersonasSnapshot>>
    listPublishIndex: () => Promise<RemoteResult<PublishIndexRead>>
    listReviewIndex: () => Promise<RemoteResult<ReviewIndexRead>>
    listReviewTemplates: (theme: string) => Promise<RemoteResult<{ files: readonly string[]; }>>
    listTemplates: () => Promise<RemoteResult<TemplatesSnapshot>>
    moveAsset: (move: GatherAssetMove) => Promise<RemoteResult<void>>
    parseInteractionImport: (request: InteractionImportPreviewRequest) => Promise<RemoteResult<InteractionImportPreview>>
    parseReviewImport: (request: ReviewImportPreviewRequest) => Promise<RemoteResult<ReviewImportPreview>>
    processMaterial: (request: GatherAiRequest) => Promise<RemoteResult<GatherAiResult>>
    processPersonaAi: (request: PersonaAiRequest) => Promise<RemoteResult<PersonaAiResult>>
    processTemplateAi: (request: TemplateAiRequest) => Promise<RemoteResult<TemplateAiResult>>
    publishCreateFinal: (theme: string, request: CreatePublishRequest) => Promise<RemoteResult<CreatePublishResult>>
    putCreateTemplate: (input: CreateTemplateInput) => Promise<RemoteResult<CreateTemplateList>>
    putPersona: (input: PersonaInput) => Promise<RemoteResult<PersonaEntry>>
    putPersonaReport: (id: PersonaId, report: PersonaReport) => Promise<RemoteResult<PersonaEntry>>
    putTemplate: (input: TemplateInput) => Promise<RemoteResult<TemplateRecord>>
    putTemplateTags: (tags: readonly TemplateTag[]) => Promise<RemoteResult<readonly TemplateTag[]>>
    readAsset: (theme: string, file: string) => Promise<RemoteResult<{ content?: string; }>>
    readCompetitorManifest: (theme: string) => Promise<RemoteResult<CompetitorManifestRead>>
    readCreateMetadata: (theme: string) => Promise<RemoteResult<{ metadata: OutputMetadata | null; problem: string | null; }>>
    readCreateState: (theme: string) => Promise<RemoteResult<CreateStateRead>>
    readGatherManifest: (theme: string) => Promise<RemoteResult<GatherManifestRead>>
    readInteractions: () => Promise<RemoteResult<InteractionsManifestRead>>
    readPublishDerived: (theme: string, taskId: string, platformId: string) => Promise<RemoteResult<{ content?: string; }>>
    readPublishManifest: (theme: string) => Promise<RemoteResult<PublishManifestRead>>
    readPublishProfiles: () => Promise<RemoteResult<PublishProfilesRead>>
    readPublishSource: (theme: string, file: string) => Promise<RemoteResult<{ content?: string; }>>
    readReviewManifest: (theme: string) => Promise<RemoteResult<ReviewManifestRead>>
    readReviewReport: (theme: string, file: string) => Promise<RemoteResult<ReviewReportRead>>
    readReviewTemplate: (theme: string, file: string) => Promise<RemoteResult<ReviewReportRead>>
    registerCreatePublish: (theme: string, request: CreateRegisterRequest) => Promise<RemoteResult<void>>
    rewriteCreateSelection: (request: CreateRewriteRequest) => Promise<RemoteResult<CreateAiResult>>
    sendInteractionReply: (request: InteractionSendReplyRequest) => Promise<RemoteResult<{ ok: false; reason: 'MCP_NOT_CONFIGURED'; }>>
    setTemplateStatus: (id: TemplateId, status: TemplateStatus) => Promise<RemoteResult<TemplateRecord>>
    writeAsset: (write: GatherAssetWrite) => Promise<RemoteResult<{ truncated: boolean; }>>
    writeCompetitorManifest: (theme: string, manifest: CompetitorManifest) => Promise<RemoteResult<void>>
    writeCreateMetadata: (theme: string, metadata: OutputMetadata) => Promise<RemoteResult<void>>
    writeCreateState: (theme: string, manifest: CreateManifest) => Promise<RemoteResult<void>>
    writeGatherManifest: (theme: string, manifest: GatherManifest) => Promise<RemoteResult<GatherManifest>>
    writeInteractions: (manifest: InteractionsManifest) => Promise<RemoteResult<InteractionsManifest>>
    writePublishDerived: (theme: string, taskId: string, platformId: string, content: string) => Promise<RemoteResult<{ file: string; }>>
    writePublishManifest: (theme: string, manifest: PublishManifest) => Promise<RemoteResult<void>>
    writePublishProfiles: (profiles: PublishProfilesDoc['profiles']) => Promise<RemoteResult<void>>
    writeReviewManifest: (theme: string, manifest: ReviewManifest) => Promise<RemoteResult<void>>
    writeReviewReport: (theme: string, file: string, content: string) => Promise<RemoteResult<{ file: string; }>>
    writeReviewTemplate: (theme: string, file: string, content: string) => Promise<RemoteResult<{ file: string; }>>
  }
  interface TypertRemoteMap {
    'contentOutputs/adaptPublishContent': (request: PublishAdaptRequest) => Promise<RemoteResult<PublishAdaptResult>>
    'contentOutputs/analyzeCompetitorWork': (request: CompetitorAnalyzeWorkRequest) => Promise<RemoteResult<CompetitorAnalyzeWorkResult>>
    'contentOutputs/analyzeReviewWork': (request: ReviewAnalyzeWorkRequest) => Promise<RemoteResult<ReviewAiResult>>
    'contentOutputs/buildPublishPackage': (theme: string, taskId: string) => Promise<RemoteResult<PublishPackage>>
    'contentOutputs/classifyInteractions': (request: InteractionClassifyRequest) => Promise<RemoteResult<InteractionClassifyResult>>
    'contentOutputs/commitInteractionImport': (request: InteractionImportCommitRequest) => Promise<RemoteResult<InteractionImportCommitResult>>
    'contentOutputs/commitReviewImport': (request: ReviewImportCommitRequest) => Promise<RemoteResult<ReviewImportCommitResult>>
    'contentOutputs/deleteAsset': (theme: string, file: string) => Promise<RemoteResult<void>>
    'contentOutputs/deleteCreateTemplate': (id: string) => Promise<RemoteResult<CreateTemplateList>>
    'contentOutputs/deletePersona': (id: PersonaId) => Promise<RemoteResult<void>>
    'contentOutputs/deleteReviewTask': (request: ReviewTaskDeleteRequest) => Promise<RemoteResult<void>>
    'contentOutputs/deleteTemplate': (id: TemplateId) => Promise<RemoteResult<void>>
    'contentOutputs/evaluateCreateContent': (request: CreateEvaluateRequest) => Promise<RemoteResult<CreateEvaluation>>
    'contentOutputs/exportInteractionCsv': () => Promise<RemoteResult<{ text: string; }>>
    'contentOutputs/exportTemplates': (ids: readonly string[]) => Promise<RemoteResult<TemplatePack>>
    'contentOutputs/extractInteractionInsights': (request: InteractionInsightRequest) => Promise<RemoteResult<InteractionInsightResult>>
    'contentOutputs/fetchFeed': (request: GatherFeedRequest, signal?: AbortSignal) => Promise<RemoteResult<GatherFeedResult>>
    'contentOutputs/generateCompetitorReport': (request: CompetitorReportRequest) => Promise<RemoteResult<CompetitorReportResult>>
    'contentOutputs/generateCreateContent': (request: CreateGenerateRequest) => Promise<RemoteResult<CreateAiResult>>
    'contentOutputs/generateInteractionReply': (request: InteractionReplyRequest) => Promise<RemoteResult<InteractionReplyResult>>
    'contentOutputs/generateReviewReport': (request: ReviewGenerateReportRequest) => Promise<RemoteResult<ReviewAiResult>>
    'contentOutputs/getPersona': (id: PersonaId) => Promise<RemoteResult<{ persona?: PersonaEntry; }>>
    'contentOutputs/getTemplateHistory': (id: TemplateId) => Promise<RemoteResult<TemplateHistoryRead>>
    'contentOutputs/importTemplates': (pack: TemplatePack, strategy: TemplateImportStrategy) => Promise<RemoteResult<TemplateImportSummary>>
    'contentOutputs/list': () => Promise<RemoteResult<ContentOutputsSnapshot>>
    'contentOutputs/listCreateAssets': (theme: string) => Promise<RemoteResult<CreateAssetList>>
    'contentOutputs/listCreateTemplates': () => Promise<RemoteResult<CreateTemplateList>>
    'contentOutputs/listPersonas': () => Promise<RemoteResult<PersonasSnapshot>>
    'contentOutputs/listPublishIndex': () => Promise<RemoteResult<PublishIndexRead>>
    'contentOutputs/listReviewIndex': () => Promise<RemoteResult<ReviewIndexRead>>
    'contentOutputs/listReviewTemplates': (theme: string) => Promise<RemoteResult<{ files: readonly string[]; }>>
    'contentOutputs/listTemplates': () => Promise<RemoteResult<TemplatesSnapshot>>
    'contentOutputs/moveAsset': (move: GatherAssetMove) => Promise<RemoteResult<void>>
    'contentOutputs/parseInteractionImport': (request: InteractionImportPreviewRequest) => Promise<RemoteResult<InteractionImportPreview>>
    'contentOutputs/parseReviewImport': (request: ReviewImportPreviewRequest) => Promise<RemoteResult<ReviewImportPreview>>
    'contentOutputs/processMaterial': (request: GatherAiRequest) => Promise<RemoteResult<GatherAiResult>>
    'contentOutputs/processPersonaAi': (request: PersonaAiRequest) => Promise<RemoteResult<PersonaAiResult>>
    'contentOutputs/processTemplateAi': (request: TemplateAiRequest) => Promise<RemoteResult<TemplateAiResult>>
    'contentOutputs/publishCreateFinal': (theme: string, request: CreatePublishRequest) => Promise<RemoteResult<CreatePublishResult>>
    'contentOutputs/putCreateTemplate': (input: CreateTemplateInput) => Promise<RemoteResult<CreateTemplateList>>
    'contentOutputs/putPersona': (input: PersonaInput) => Promise<RemoteResult<PersonaEntry>>
    'contentOutputs/putPersonaReport': (id: PersonaId, report: PersonaReport) => Promise<RemoteResult<PersonaEntry>>
    'contentOutputs/putTemplate': (input: TemplateInput) => Promise<RemoteResult<TemplateRecord>>
    'contentOutputs/putTemplateTags': (tags: readonly TemplateTag[]) => Promise<RemoteResult<readonly TemplateTag[]>>
    'contentOutputs/readAsset': (theme: string, file: string) => Promise<RemoteResult<{ content?: string; }>>
    'contentOutputs/readCompetitorManifest': (theme: string) => Promise<RemoteResult<CompetitorManifestRead>>
    'contentOutputs/readCreateMetadata': (theme: string) => Promise<RemoteResult<{ metadata: OutputMetadata | null; problem: string | null; }>>
    'contentOutputs/readCreateState': (theme: string) => Promise<RemoteResult<CreateStateRead>>
    'contentOutputs/readGatherManifest': (theme: string) => Promise<RemoteResult<GatherManifestRead>>
    'contentOutputs/readInteractions': () => Promise<RemoteResult<InteractionsManifestRead>>
    'contentOutputs/readPublishDerived': (theme: string, taskId: string, platformId: string) => Promise<RemoteResult<{ content?: string; }>>
    'contentOutputs/readPublishManifest': (theme: string) => Promise<RemoteResult<PublishManifestRead>>
    'contentOutputs/readPublishProfiles': () => Promise<RemoteResult<PublishProfilesRead>>
    'contentOutputs/readPublishSource': (theme: string, file: string) => Promise<RemoteResult<{ content?: string; }>>
    'contentOutputs/readReviewManifest': (theme: string) => Promise<RemoteResult<ReviewManifestRead>>
    'contentOutputs/readReviewReport': (theme: string, file: string) => Promise<RemoteResult<ReviewReportRead>>
    'contentOutputs/readReviewTemplate': (theme: string, file: string) => Promise<RemoteResult<ReviewReportRead>>
    'contentOutputs/registerCreatePublish': (theme: string, request: CreateRegisterRequest) => Promise<RemoteResult<void>>
    'contentOutputs/rewriteCreateSelection': (request: CreateRewriteRequest) => Promise<RemoteResult<CreateAiResult>>
    'contentOutputs/sendInteractionReply': (request: InteractionSendReplyRequest) => Promise<RemoteResult<{ ok: false; reason: 'MCP_NOT_CONFIGURED'; }>>
    'contentOutputs/setTemplateStatus': (id: TemplateId, status: TemplateStatus) => Promise<RemoteResult<TemplateRecord>>
    'contentOutputs/writeAsset': (write: GatherAssetWrite) => Promise<RemoteResult<{ truncated: boolean; }>>
    'contentOutputs/writeCompetitorManifest': (theme: string, manifest: CompetitorManifest) => Promise<RemoteResult<void>>
    'contentOutputs/writeCreateMetadata': (theme: string, metadata: OutputMetadata) => Promise<RemoteResult<void>>
    'contentOutputs/writeCreateState': (theme: string, manifest: CreateManifest) => Promise<RemoteResult<void>>
    'contentOutputs/writeGatherManifest': (theme: string, manifest: GatherManifest) => Promise<RemoteResult<GatherManifest>>
    'contentOutputs/writeInteractions': (manifest: InteractionsManifest) => Promise<RemoteResult<InteractionsManifest>>
    'contentOutputs/writePublishDerived': (theme: string, taskId: string, platformId: string, content: string) => Promise<RemoteResult<{ file: string; }>>
    'contentOutputs/writePublishManifest': (theme: string, manifest: PublishManifest) => Promise<RemoteResult<void>>
    'contentOutputs/writePublishProfiles': (profiles: PublishProfilesDoc['profiles']) => Promise<RemoteResult<void>>
    'contentOutputs/writeReviewManifest': (theme: string, manifest: ReviewManifest) => Promise<RemoteResult<void>>
    'contentOutputs/writeReviewReport': (theme: string, file: string, content: string) => Promise<RemoteResult<{ file: string; }>>
    'contentOutputs/writeReviewTemplate': (theme: string, file: string, content: string) => Promise<RemoteResult<{ file: string; }>>
  }
  interface TypertRemoteNamespaceMap {
    'contentOutputs': TypertRemoteNamespace$636f6e74656e744f757470757473
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
